# Fail and Win Jobs

jobs:
# - job: Fail
#   displayName: Docker Build Fail Demo
#   continueOnError: true
#   pool:
#     vmImage: 'Ubuntu-16.04'
#   steps:
#   - script: ./build-docker-fail.sh
- job: Win
  displayName: Kaniko Build Win Demo
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  # The cache is simply to demonstrate using cache.
  # It doesn't have any effect in Azure Pipelines
  - script: ./warm-kaniko-cache.sh
  - script: ./build-kaniko-win.sh
